### ISSUE TITLE
如何使用?

### ISSUE THREAD

**Issue by caichunjian520** [ISNing/WearInstaller#1]
我在AS上将代码运行到手机后发现只有一些设置的开关选项, 还有一个清理安装包的功能. 我现在自己有个wearos的apk需要安装到wearos手表上, 是需要将apk放到provider_paths.xml里对应的path,并且将xml里的name改成apk一样的名称么?

求解答, 感谢

**Comment by isning** [comment]
从文件管理器或者其他软件中打开apk文件，会自动拉起这个app，进行安装

**Comment by caichunjian520** [comment]
感谢

**Comment by caichunjian520** [comment]
这个是不是需要手表root才能安装, 我在文件管理器中点开apk,就当做手机端的apk那样问是否安装, 输入密码, 因为这个是wear的apk, 所以手机端安装失败, 并没有打开Wear安装器的app

**Comment by isning** [comment]
你需要先用adb把这个安装器的包安装的手表上，在手表上打开WiFi adb调试，配好对，之后就可以在手表上的文件管理里安装安装手表本地的apk文件了
